use anchor_lang::error_code;

#[error_code]
pub enum MultisigErrors {
    MaxAccountNameLength,
    MaxSignatories,
    MultisigCreatorIsNotSigner,
    MaxThreshold,
    MaxCalldataSize,
    InvalidProposer,
    InvalidMint,
    InvalidVoter,
    ProposalAlreadyVoted,
    InvalidExecutor,
    NotEnoughVotes,
    AlreadyExecuted,
    InvalidMintToPubkey,
    InvalidMintToATA,
    InvalidTransferToPubkey,
    InvalidTransferFromPubkey,
    InvalidSellerPubkey,
    InvalidSellerATA,
    InvalidBuyerPubkey,
    InvalidBuyerATA,
    MintToAccountIsNull,
    MintToTokenAccountIsNull,
    TransferFromAccountIsNull,
    TransferFromTokenAccountIsNull,
    InvalidTransferFromATA,
    TransferToAccountIsNull,
    TransferToTokenAccountIsNull,
    InvalidTransferToATA,
    SellerAccountIsNull,
    SellerTokenAccountIsNull,
    BuyerAccountIsNull,
    BuyerTokenAccountIsNull,
}
