[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
proposal_system = "D9es5JgK89P3DHSDdD2bFnn3iYzc5ygRA789Sp4VUtJ2"

[programs.devnet]
proposal_system = "2F3xVyraFXuZpCShqg2YVuF5HxNukmGtGdkm5fJ41L3R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/archana/.config/solana/id.json"

[provider.devnet]
cluster = "devnet"
wallet = "/home/archana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
